name: Transfer Data Daily

# Trigger every day at 2:00 PM Lebanon time
on:
  schedule:
    - cron: '10 12 * * *'   
  workflow_dispatch:        # allows manual trigger

jobs:
  call_api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Laravel API
        run: |
          curl -X POST "https://laravelwordpressapi.onrender.com/api/transferData" \
          -H "X-API-KEY: ${{ secrets.SCHEDULER_KEY }}"
